apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-1 
spec:
  config: '{
      "cniVersion": "0.4.0",
      "name": "bridge-test",
      "type": "bridge",
      "capabilities": { "ips": true },
      "bridge": "br1",
      "ipam": {
        "type": "static",
          "addresses": [
                        {
                          "address": "172.16.32.226/24",
                          "gateway": "172.16.32.1"
                        }
                    ]
      }
    }'
