apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cirros-v
  labels:
    kubevirt.io/vm: cirros-v 
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: cirros-v
      spec:
        source:
          registry:
            url: 'docker://kubevirt/cirros-container-disk-demo:latest'
        storage:
          storageClassName: managed-nfs-storage
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: cirros-v
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
        resources:
          requests:
            memory: 0.1Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: cirros-v2 
          name: rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: my-vmi-secret
