apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: nginx-provisioner
  name: cirros-openstack-vm 
  namespace: default
spec:
  runStrategy: "RerunOnFailure"
  template:
    metadata:
      labels:
        kubevirt.io/vm: nginx-provisioner
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: fedora-nginx
        name: datavolumedisk1 
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh
            # removing instances ensures cloud init will execute again after reboot
            mkdir ~/123
            sudo echo -e "zlinux\nzlinux" | passwd root
            rm -rf /var/lib/cloud/instances
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: fedora-nginx
    spec:
      storage:
        storageClassName: managed-nfs-storage
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
      source: # clone from source dv
        pvc:
          namespace: vm-images
          name: cirros-dv # the dv need prepare 
