apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens224",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "172.16.32.0/24",
        "rangeStart": "172.16.32.226",
        "rangeEnd": "172.16.32.228",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "172.16.32.1"
      }
    }'
